M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu21.10.1} date Sat 15 Jan 2022 20:43:22 CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-15T20:43:22-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu21.10.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
%
G90
G05
T1
X15.5712Y-14.178
T0
M30
